### ISSUE TITLE
User stats requests

### ISSUE THREAD

**Issue by brettalcox** [brettalcox/logU-swift#11]
- <strike>Wilks score</strike>
- Rate of growth
- <strike>Average set/rep</strike>
- <strike>Frequency of workouts by week/month/year</strike>
- Training percentage by week/month/year
- <strike>Most performed (favorite) lift</strike>
- <strike>Lift breakdown graph</strike>
- Highest growth
- Least growth 
- <strike>Total lifts, total sets, total reps</strike>
- <strike>Frequency of workouts by week(list)</strike> 
- <strike>Average frequency of workouts</strike> 
- <strike>Tooltip(s) on (?) help button press on the User Stats page (to give info on all of the stats and what they are)</strike> 
- <strike>Strength Level (intermediate, advanced, etc.)</strike> 
- <strike>Percentile rank in the community of logU</strike>
- <strike>Radar chart of growth/development/deficiencies</strike>

**Comment by jaredbaj** [comment]
Ranks against all users of the app? Maybe you gotta post a pic/vid for verification ;)

**Comment by jaredbaj** [comment]
Having a dashboard that showed all of these quickly would be great, too. Maybe a percentile chart that shows how you rank to the average human with similar stats (weight/height/age)?

**Comment by brettalcox** [comment]
Wilks, average rep, number of reps, number of sets, number of logged lifts queries have been written. Wilks utilizes gender and body weight, so both of those attributes have been added to database. Will need to add fields to user settings to update those accordingly.

**Comment by brettalcox** [comment]
Wilks, average rep, number of reps, number of sets, number of logged lifts methods have been written and implemented (will push later).

**Comment by brettalcox** [comment]
rep_average.php script has been updated for favorite lift

**Comment by brettalcox** [comment]
Probably a good start for now. May reopen down the road for new features.

**Comment by brettalcox** [comment]
v1.3 will include at least:
- <strike>Frequency of workouts by week(list)</strike> - Done
- <strike>Average frequency of workouts</strike> - Done
- <strike>Tooltip(s) on (?) help button press on the User Stats page (to give info on all of the stats and what they are)</strike> - Done
- <strike>Strength Level (intermediate, advanced, etc.)</strike> - Done

Potential additions starting ~around v1.3:
- <strike>Percentile rank in the community of logU</strike> - Done
- Wilks increase/decrease/growth
- <strike>Radar chart of growth/development/deficiencies</strike> - Done
